-- ===========================================================================
--  001_core — базовая схема. Обычный PostgreSQL, без TimescaleDB.
--  Выполняется приложением при старте, идемпотентно.
--
--  Качество значения (семантика OPC UA):
--    0 GOOD        значение прочитано и декодировано успешно
--    1 BAD_COMM    нет связи с устройством / таймаут / Modbus exception
--    2 BAD_RANGE   значение вне заданных min/max
--    3 BAD_DECODE  ошибка декодирования
--    4 STALE       значение не обновлялось, записано как «сердцебиение»
-- ===========================================================================

-- --------------------------------------------------------------------------
--  Иерархия цифрового двойника: площадка → участок → линия → машина
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS twin_node (
    node_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   integer REFERENCES twin_node (node_id) ON DELETE CASCADE,
    kind        text        NOT NULL DEFAULT 'machine',   -- site|area|line|machine
    name        text        NOT NULL,
    description text,
    sort_order  integer     NOT NULL DEFAULT 0,
    meta        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT twin_node_kind_chk CHECK (kind IN ('site', 'area', 'line', 'machine'))
);

CREATE INDEX IF NOT EXISTS twin_node_parent_idx ON twin_node (parent_id);

-- --------------------------------------------------------------------------
--  Устройства (источники данных). Раньше жили в config.yaml.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS device (
    device_id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  text        NOT NULL UNIQUE,
    description           text,
    node_id               integer REFERENCES twin_node (node_id) ON DELETE SET NULL,
    transport             text        NOT NULL DEFAULT 'tcp',   -- tcp|udp|rtu
    host                  text,
    port                  integer     NOT NULL DEFAULT 502,
    unit_id               integer     NOT NULL DEFAULT 1,
    serial_port           text,
    baudrate              integer     NOT NULL DEFAULT 9600,
    bytesize              integer     NOT NULL DEFAULT 8,
    parity                text        NOT NULL DEFAULT 'N',
    stopbits              integer     NOT NULL DEFAULT 1,
    timeout_s             double precision NOT NULL DEFAULT 3.0,
    retries               integer     NOT NULL DEFAULT 2,
    reconnect_delay_s     double precision NOT NULL DEFAULT 2.0,
    reconnect_delay_max_s double precision NOT NULL DEFAULT 30.0,
    inter_request_delay_ms integer    NOT NULL DEFAULT 0,
    block_max_registers   integer     NOT NULL DEFAULT 100,
    block_max_gap         integer     NOT NULL DEFAULT 8,
    enabled               boolean     NOT NULL DEFAULT true,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT device_transport_chk CHECK (transport IN ('tcp', 'udp', 'rtu'))
);

COMMENT ON TABLE device IS 'Опрашиваемые устройства. Управляется из веб-интерфейса.';

-- --------------------------------------------------------------------------
--  Справочник тегов
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tag (
    tag_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device       text        NOT NULL,          -- имя устройства (для Grafana)
    name         text        NOT NULL,
    description  text,
    unit         text,
    datatype     text        NOT NULL,
    register     text        NOT NULL,
    address      integer     NOT NULL,
    bit          smallint,
    scale        double precision NOT NULL DEFAULT 1,
    "offset"     double precision NOT NULL DEFAULT 0,
    min_value    double precision,
    max_value    double precision,
    labels       jsonb       NOT NULL DEFAULT '{}'::jsonb,
    enabled      boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tag_device_name_key UNIQUE (device, name)
);

-- Поля, которых не было в первой версии проекта: добавляем безопасно.
ALTER TABLE tag ADD COLUMN IF NOT EXISTS device_id       integer REFERENCES device (device_id) ON DELETE CASCADE;
ALTER TABLE tag ADD COLUMN IF NOT EXISTS node_id         integer REFERENCES twin_node (node_id) ON DELETE SET NULL;
ALTER TABLE tag ADD COLUMN IF NOT EXISTS length          integer;
ALTER TABLE tag ADD COLUMN IF NOT EXISTS word_order      text NOT NULL DEFAULT 'big';
ALTER TABLE tag ADD COLUMN IF NOT EXISTS byte_order      text NOT NULL DEFAULT 'big';
ALTER TABLE tag ADD COLUMN IF NOT EXISTS poll_interval_ms integer NOT NULL DEFAULT 1000;
ALTER TABLE tag ADD COLUMN IF NOT EXISTS deadband        double precision NOT NULL DEFAULT 0;
ALTER TABLE tag ADD COLUMN IF NOT EXISTS deadband_mode   text NOT NULL DEFAULT 'absolute';
ALTER TABLE tag ADD COLUMN IF NOT EXISTS heartbeat_s     double precision NOT NULL DEFAULT 60;
ALTER TABLE tag ADD COLUMN IF NOT EXISTS group_name      text;
-- Роль тега в мнемосхеме/дашборде: value|state|alarm|counter|setpoint
ALTER TABLE tag ADD COLUMN IF NOT EXISTS role            text NOT NULL DEFAULT 'value';

CREATE INDEX IF NOT EXISTS tag_device_idx    ON tag (device);
CREATE INDEX IF NOT EXISTS tag_device_id_idx ON tag (device_id);
CREATE INDEX IF NOT EXISTS tag_node_idx      ON tag (node_id);
CREATE INDEX IF NOT EXISTS tag_labels_idx    ON tag USING gin (labels);

-- --------------------------------------------------------------------------
--  Значения
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tag_value (
    ts          timestamptz      NOT NULL,
    tag_id      integer          NOT NULL REFERENCES tag (tag_id) ON DELETE CASCADE,
    value       double precision,
    value_text  text,
    quality     smallint         NOT NULL DEFAULT 0
);

-- Основной паттерн запроса Grafana: «один тег за интервал времени»
CREATE INDEX IF NOT EXISTS tag_value_tag_ts_idx ON tag_value (tag_id, ts DESC);
-- BRIN дёшево ускоряет отсечение по времени на большой таблице без Timescale
CREATE INDEX IF NOT EXISTS tag_value_ts_brin_idx ON tag_value USING brin (ts);

-- --------------------------------------------------------------------------
--  Представления
-- --------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_tag_value AS
SELECT v.ts,
       v.value,
       v.value_text,
       v.quality,
       t.tag_id,
       t.device,
       t.name,
       t.description,
       t.unit,
       t.labels,
       t.device || '.' || t.name AS full_name
FROM tag_value v
JOIN tag t USING (tag_id);

CREATE OR REPLACE VIEW v_tag_latest AS
SELECT DISTINCT ON (t.tag_id)
       t.tag_id,
       t.device,
       t.name,
       t.description,
       t.unit,
       t.labels,
       t.node_id,
       t.role,
       t.group_name,
       v.ts,
       v.value,
       v.value_text,
       v.quality,
       now() - v.ts AS age
FROM tag t
LEFT JOIN tag_value v ON v.tag_id = t.tag_id
WHERE t.enabled
ORDER BY t.tag_id, v.ts DESC;

-- Полный путь узла двойника: «Завод / Линия 1 / Розлив»
CREATE OR REPLACE VIEW v_twin_path AS
WITH RECURSIVE walk AS (
    SELECT node_id, parent_id, kind, name, name AS path, 1 AS depth
    FROM twin_node WHERE parent_id IS NULL
    UNION ALL
    SELECT n.node_id, n.parent_id, n.kind, n.name,
           w.path || ' / ' || n.name, w.depth + 1
    FROM twin_node n JOIN walk w ON n.parent_id = w.node_id
)
SELECT node_id, parent_id, kind, name, path, depth FROM walk;
